<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_nav-btn-login</name>
   <tag></tag>
   <elementGuidId>2e633420-f7aa-4138-a3b9-27ca7a8e77d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nav-btn-login' and (text() = 'Sign In' or . = 'Sign In')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'nav-btn-login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;nav-btn-login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;nav-btn-login&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f62a231-f4dd-4ffb-a288-684b4469a7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-btn-login</value>
      <webElementGuid>a1f15064-d20b-4b95-bf31-9a3006b6e461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>nav-btn-login</value>
      <webElementGuid>09c8e8fe-80a7-4bf9-833a-838efb4186c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 py-1.5 text-xs font-semibold text-slate-700 hover:text-indigo-600 hover:bg-slate-100 rounded-lg transition</value>
      <webElementGuid>c17dbbb5-2a7d-431f-b8f8-dcadd67ec30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>64084c65-3f4e-4add-aeab-44703ff7edf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-15c612ee5573eaba1b0b67bbed02bd2a</value>
      <webElementGuid>0f270098-8976-496e-9596-a433073e051b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'nav-btn-login']</value>
      <webElementGuid>3988dd75-620b-400e-99b8-3b2e963eb31b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'nav-btn-login']</value>
      <webElementGuid>2567f5b7-aa09-4988-b5ba-f4dcb007800d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nav-btn-login' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>83bdd5a6-facb-44e9-9b1b-a266a572eb6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
