<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_nav-btn-login</name>
   <tag></tag>
   <elementGuidId>848e1224-a334-49ee-ace4-0cf014b1d8fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nav-btn-login' and (text() = 'Sign In' or . = 'Sign In')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'nav-btn-login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;nav-btn-login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;nav-btn-login&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13546c0f-7c94-4136-b52f-8840872651fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-btn-login</value>
      <webElementGuid>4493da53-2a8b-4ba5-82fd-99704b5fd163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>nav-btn-login</value>
      <webElementGuid>7ab34184-e72d-47bf-b400-a47c5429f6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 py-1.5 text-xs font-semibold text-slate-700 hover:text-indigo-600 hover:bg-slate-100 rounded-lg transition</value>
      <webElementGuid>1b7ae133-540c-4254-800b-d7f5831e401d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>32714809-92cf-4515-9c67-aea1c4dee772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-15c612ee5573eaba1b0b67bbed02bd2a</value>
      <webElementGuid>db9c74cc-d71f-413e-8f8a-4f12332162f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'nav-btn-login']</value>
      <webElementGuid>7ae13c79-9a32-4be6-9b6d-6834800b290f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'nav-btn-login']</value>
      <webElementGuid>d9045f14-8ad2-4e03-b1df-9f598bc6edde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nav-btn-login' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>979c86e0-2c30-463e-abff-c2ea5d39d778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
