<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_e.g. QA20</name>
   <tag></tag>
   <elementGuidId>e515e621-6ac4-4d47-b825-c70f8bab214f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'input-coupon-code' and @placeholder = 'e.g. QA20' and @type = 'text' and @name = 'couponCode']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'input-coupon-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;input-coupon-code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;input-coupon-code&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a1de163-954f-4ab5-ae72-e32179b49c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-coupon-code</value>
      <webElementGuid>9032a10a-d904-4de3-ac6c-1392aa848091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-coupon-code</value>
      <webElementGuid>07281d20-d028-40f8-b4fd-bb33a23ac643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. QA20</value>
      <webElementGuid>0fef1947-b57b-4c55-a039-5e2088ce138a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 px-3 py-2 bg-slate-50 border rounded-xl text-xs uppercase font-mono tracking-wider focus:outline-none focus:ring-2 border-slate-200 focus:ring-indigo-500/20 focus:border-indigo-500</value>
      <webElementGuid>6f94946c-5758-4c69-859c-6741a6a51d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7c00934-95d9-4288-bc67-54c219ecdd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>couponCode</value>
      <webElementGuid>544d4af4-7403-4e57-8220-780956cc2368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6ce0684f1090c92862f6394b4b3cf453</value>
      <webElementGuid>3ba9543e-b01c-4ca9-991f-4e72a5cd3138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'input-coupon-code']</value>
      <webElementGuid>b7fdee3b-d2d6-406d-8a1e-05e7654bab11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'input-coupon-code']</value>
      <webElementGuid>bf1fff55-6772-4fde-854e-2cf66eadfffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-coupon-code' and @placeholder = 'e.g. QA20' and @type = 'text' and @name = 'couponCode']</value>
      <webElementGuid>477b2157-193d-445e-9625-0655dc451ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
