<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_nav-btn-register</name>
   <tag></tag>
   <elementGuidId>ccc637cb-b14a-4c6c-9b47-7ce0cae1ea44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nav-btn-register' and (text() = 'Register' or . = 'Register')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'nav-btn-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;nav-btn-register&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;nav-btn-register&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b909a015-f8be-48cd-a2c0-c19e7c816d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-btn-register</value>
      <webElementGuid>cec6b0e2-02e7-41d5-b5cf-9deb88b51cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>nav-btn-register</value>
      <webElementGuid>4eec5490-c645-4fb9-bfb7-e810ff94e0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3.5 py-1.5 text-xs font-semibold bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg shadow-sm transition</value>
      <webElementGuid>dab5965f-f32d-4721-90d8-bdf79c5b62fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>f700f6ce-0796-47d5-91f2-b802496c3d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-135cdd63d0dce97f451c274b771e511c</value>
      <webElementGuid>79fc91eb-c44f-4f26-8ac1-61ce6c3837e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'nav-btn-register']</value>
      <webElementGuid>1bb464a5-7f62-44b2-bfd2-739e9b9c6f66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'nav-btn-register']</value>
      <webElementGuid>8adbb8b5-61ab-475b-97ea-6f8be7324b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nav-btn-register' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>eb4e2adb-3e58-49ce-ab95-cb0777aaa261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
