<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox-reg-terms</name>
   <tag></tag>
   <elementGuidId>2dedd74e-d321-40d5-ac19-5b56c0b95a4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'checkbox-reg-terms' and @type = 'checkbox' and @name = 'terms']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'checkbox-reg-terms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;checkbox-reg-terms&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;checkbox-reg-terms&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50614abe-5a94-4adc-9f4d-d5e728010370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-reg-terms</value>
      <webElementGuid>d47f50a0-3dcc-431b-bcd1-533eeda4eb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>checkbox-reg-terms</value>
      <webElementGuid>b4bbde65-58f9-4e0b-b9da-a2f25dacb7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-0.5 w-3.5 h-3.5 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500 cursor-pointer</value>
      <webElementGuid>8a93b404-713b-45c1-beb4-b6108ddbfbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1dc5e7e8-3198-4f01-b1c3-e06474b41ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>88be87e6-b64a-48d5-b7b7-45b9e25c081f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-01dd8da58501d2b4e3e1ab7fd15da741</value>
      <webElementGuid>486b31cb-b1f5-41ec-bc7f-52f239459b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'checkbox-reg-terms']</value>
      <webElementGuid>0263ac0f-fd20-443f-970b-a9274b1b656e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'checkbox-reg-terms']</value>
      <webElementGuid>f5ac9386-16ae-457d-b5f8-c4b65326bc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-reg-terms' and @type = 'checkbox' and @name = 'terms']</value>
      <webElementGuid>d0ba1d5c-c580-4e6e-81c8-cb6bcddbfb9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
